on: [push]

jobs:
  start_scan:
    runs-on: ubuntu-latest
    name: A job to run a Nexploit scan
    steps:
    - name: Start Nexploit Scan
      id: start
      uses: NeuraLegion/run-scan@master
      with:
        api_token: ${{ secrets.NEXPLOIT_TOKEN }}
#        restart_scan: ai3LG8DmVn9Rn1YeqCNRGQ
        name: GitHub scan ${{ github.sha }}
        discovery_types: |
          [ "crawler", "archive" ]
        crawler_urls: |
          [ "https://juice-shop.herokuapp.com" ]
        file_id: LiYknMYSdbSZbqgMaC9Sj
        hosts_filter: |
          [ ]
    - name: Get the output scan url
      run: echo "The scan was started on ${{ steps.start.outputs.url }}"
