on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: NeuraLegion/ghaction@master
      with:
        api_token: 'Mona the Octocat'
        discovery_types: | 
          [ "arhive", "crawler" ]
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
